Feature/blog create api
alyonastartseva/blogging-platform-2 pull request #10
Opened 2023-10-02 14:50 UTC by sc509

Closes 6

2023-10-03 17:33 UTC, M1sterRob0t commented
Ну и сам запрос неправильно сконфигурирован, посмотри внимательно, что получается на выходе.
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/ab9080b7-7102-46c1-b673-f91f6f48e8aa)

2023-10-05 11:47 UTC, winston-0 commented on src/modules/CreateBlogForm/store/store.ts
> +    middleware:(getDefaultMiddleware) => getDefaultMiddleware().concat(platformApi.middleware)
store должен инициализироваться глобально, а в модулях хранятся апишки и слайсы

2023-10-05 14:26 UTC, Sv812asx commented
Правки сделаны

2023-10-06 08:21 UTC, M1sterRob0t commented
1.  Base_URL глобальная константа, используемая на уровне всего проекта. Вынести в shared/constants.ts => SERVER_URL
2. название редьюсера platformApi, но редьюсер отвечает за создание блога. Вместо того чтобы рассказывать о том, что делает код, имя твоей переменной дезинформирует
3. в корне модуля файл index.ts, который реэкспортирует редьюсер и компонент. Из недр модуля ничего не экспортируем
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/eb194b25-11c9-46c8-a1b3-08c83885d473)
4. Серверная структура блога:
{
      "id": 1,
      "date": "2023-09-27T14:22:12.290Z",
      "title": "Elliot Blog 1",
      "cover": "https://i0.wp.com/showspy.ru/wp-content/uploads/2020/03/mr-robot-poster.jpg?ssl=1",
      "author": {
        "username": "Elliot Alderson",
        "avatar": "https://assets2.ignimgs.com/2016/08/29/mr-robotjpg-42cabf.jpg?width=300"
      },
      "articles": [{}, {}, {}]
 }
 
 Твоя структура блога:
      "title": "2",
      "cover": null,
      "author": {
        "username": "2"
      },
      "date": "2023-10-05T14:11:48.283Z",
      "id": 4
    },
   В реальном приложении тебе сервер просто ответит 500 ошибкой. Добавь недостающие поля.

2023-10-06 08:25 UTC, M1sterRob0t commented
Название коммита должно описывать, какие изменения были внесены. 
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/e891bff0-0950-471e-9626-bfe3efcd22e7)
На работе за такие коммиты уволят в первый же день :)

2023-10-10 15:16 UTC, alyonastartseva requested changes

2023-10-10 15:16 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +    const handleSubmit = async () => {
лучше оставить этот компонент "глупым", а колбэк для запроса передавать извне

2023-10-10 15:16 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +        try {
раздели на несколько подметодов, чтобы читабельнее было

2023-10-10 15:16 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +                            key: 'e9666c2a991bf171d0ea02a4d0ccdad8',
может в константу стоит вынести ключ?

2023-10-10 15:16 UTC, alyonastartseva commented on src/store/store.ts
> -});
```
const middlewares = [ 1, 2, N ];
concat(middlewares)
```

чтобы не было длинных цепочек

2023-10-10 15:16 UTC, alyonastartseva commented on src/types/author.ts
> +  avatar?: string | null;
undefined, null и string?

2023-10-12 09:52 UTC, Sv812asx commented on src/components/blogsList/BlogsList.tsx
> +    const reversedDataArray = [...blogsDataArray].reverse();
исправил

2023-10-12 09:53 UTC, Sv812asx commented on src/components/indexPageInputs/IndexpageInputs.module.scss
> +.modal {
Убрал

2023-10-12 10:08 UTC, Sv812asx commented on src/modules/CreateBlogForm/index.ts
> +export { default as CreateBlog } from "./СreateBlog/createBlog.tsx";
+

2023-10-12 10:08 UTC, Sv812asx commented on src/modules/CreateBlogForm/СreateBlog/createBlog.module.scss
> +.createBlogModal :global(.ant-modal-header) {
+

2023-10-12 10:14 UTC, Sv812asx commented on src/store/store.ts
> -});
Сделал

2023-10-12 10:22 UTC, Sv812asx commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +            } catch (error: any) {
+

2023-10-12 10:23 UTC, Sv812asx commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +                            key: 'e9666c2a991bf171d0ea02a4d0ccdad8',
+

2023-10-12 10:26 UTC, Sv812asx commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +        try {
+

2023-10-14 20:53 UTC, alyonastartseva requested changes

2023-10-14 20:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +            await createBlog(data as TBlogCreate);
убрать as

2023-10-14 20:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +            const apiError = error as IApiError;
убрать as

2023-10-14 20:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +                apiError &&
вот эту всю логику обработки нужно учесть в 25 задачке

2023-10-14 20:53 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +function CreateBlog({isOpen, setIsModalVisible, createNewBlog, isLoading}: CreateBlogProps & {createNewBlog: CreateNewBlogFunc}) {
а поч пропс createNewBlog не положить в CreateBlogProps?

2023-10-14 20:53 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +        return (e as { fileList: UploadFile[] })?.fileList;
здесь as тоже желательно убрать - bad practice

2023-10-14 20:53 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.type.ts
> +export interface IApiError {
этот интерфейс стоит вынести в shared

2023-10-14 20:53 UTC, alyonastartseva commented on src/shared/functions/uploadCoverImage.ts
> +export const uploadCoverImage = async (values: {coverImage: File[]}, data: Partial<TBlogCreate>) => {
может сделать так, чтобы функция не закладывалась на определенную сущность (data) с определенным типом, а возвращала url загруженного изображения просто?

2023-10-14 20:53 UTC, alyonastartseva commented on src/store/store.ts
> +let middlewares = [
почему let, а не const?

2023-10-15 10:11 UTC, Sv812asx commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +            await createBlog(data as TBlogCreate);
+

2023-10-15 11:04 UTC, Sv812asx commented on src/modules/CreateBlogForm/СreateBlog/createBlog.type.ts
> +export interface IApiError {
Заменил на класс, вынес его

2023-10-17 19:53 UTC, alyonastartseva requested changes

2023-10-17 19:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +    const createNewBlog = async (data: Partial<TBlogCreate>) => {
без Partial здесь не обойтись?

2023-10-17 19:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +            data.title !== undefined &&
это условие избыточно, если есть вариация в форме хорошая

в случае если null или undefined, то можно при создании писать так:

`title: data.title ?? ''`

2023-10-17 19:53 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +                    cover: data.cover ?? '',
cover как раз-таки у тебя так и сделан

2023-10-17 19:53 UTC, alyonastartseva commented on src/modules/CreateBlogForm/СreateBlog/createBlog.tsx
> +        let data: Partial<TBlogCreate> = {
здесь тоже хотелось бы явный тип, а не Partial

2023-10-17 19:53 UTC, alyonastartseva commented on src/shared/ApiError.ts
> +export class ApiError extends Error {
а почему именно классом?

2023-10-17 20:28 UTC, Sv812asx commented on src/shared/ApiError.ts
> +export class ApiError extends Error {
Подругому затипизировать не удалось, а с классом проблем не было при типизации

2023-10-19 11:25 UTC, alyonastartseva approved these changes

2023-10-19 23:55 UTC, merged