Closes 13 "Создать страницу просмотра выбранного блога"
alyonastartseva/blogging-platform-2 pull request #13
Opened 2023-10-03 16:04 UTC by M1sterRob0t

2023-10-04 20:56 UTC, alyonastartseva requested changes

2023-10-04 20:56 UTC, alyonastartseva commented on package.json
> +        "swiper": "^10.3.1"
Ant тож поставляет карусельку: https://ant.design/components/carousel

2023-10-04 20:56 UTC, alyonastartseva commented on src/components/blogsSlider/blogsSlider.tsx
> +    return (
return можно опустить

2023-10-04 20:56 UTC, alyonastartseva commented on src/components/blogsSlider/blogsSlider.tsx
> +            coverflowEffect={{
удобнее было бы это в объект-константу

2023-10-04 20:56 UTC, alyonastartseva commented on src/modules/articles/components/articles.tsx
> +    if (isLoading) return <p>Loading...</p>;
можно лоадер антовский заиспользовать

2023-10-04 20:56 UTC, alyonastartseva commented on src/modules/articles/components/articles.tsx
> +    if (error || !blogInfo) return <p>404. Blog is not found.</p>;
а здесь Result

2023-10-04 20:56 UTC, alyonastartseva commented on src/modules/articles/services/api.ts
> +export const BASE_URL = 'http://localhost:3001/';
BASE_URL лучше вынести в shared-константу, т.к будет использоваться не только в АПИ статей

2023-10-04 20:56 UTC, alyonastartseva commented on src/modules/articles/services/api.ts
> +export enum Endpoints {
не используется нигде

2023-10-04 20:56 UTC, alyonastartseva commented on src/modules/articles/store/store.ts
> +export const store = configureStore({
а поч в articles стор инициализируется?
он ведь должен быть общий на все модули, а вот слайсы и апи могут быть в каждом модуле
стор их будет композировать

2023-10-04 20:56 UTC, alyonastartseva commented on src/pages/blogPage/blogPage.tsx
> +  if (!blogIndex) return <p>404. Not found...</p>;
тоже красивый Result можно заиспользовать :)

2023-10-05 06:28 UTC, M1sterRob0t commented on package.json
> +        "swiper": "^10.3.1"
в antd нет сладйера с coverflow effect, как на скетче

2023-10-06 14:07 UTC, alyonastartseva requested changes

2023-10-06 14:09 UTC, alyonastartseva commented on src/modules/articles/components/articles.tsx
> +    console.log(data);
после правки можно мержить

2023-10-06 14:09 UTC, alyonastartseva approved these changes

2023-10-06 16:27 UTC, merged