Closes 17 "Реализовать просмотр комментариев у статьи + интеграция с API"
alyonastartseva/blogging-platform-2 pull request #16
Opened 2023-10-05 13:03 UTC by M1sterRob0t

Для каждой статьи в блоге добавить функционал просмотра комментариев, используя разработанную компоненту.

Данные для комментариев создать с помощью библиотеки [json-server](https://github.com/typicode/json-server), которая позволит симулировать GET-запрос для получения списка комментариев.

2023-10-14 15:47 UTC, alyonastartseva requested changes

2023-10-14 15:47 UTC, alyonastartseva commented on src/store/root-reducer.ts
> +import { articleApi } from '../modules/article';
Может по-другому стоит назвать модуль?   Article и articles очень уж похожи

При импорте с автодополнением неудобно будет :)

2023-10-14 15:47 UTC, alyonastartseva commented on src/store/store.ts
> +      .concat(articlesApi.middleware)
Конкатенировать можно и массив и чтобы не писать длинных цепочек можно так:

`const middlewares = [1,2,N] -> .concat(middlewares)`

2023-10-15 12:38 UTC, M1sterRob0t commented on json-server-middleware.js
> +  res.setHeader('Access-Control-Allow-Origin', BASE_URL);
исправлено в задании 18/19

2023-10-15 12:40 UTC, M1sterRob0t commented on src/hocs/withLoadingAndErrorHandling.tsx
> +  error: FetchBaseQueryError | SerializedError | undefined;
исправлено в задании 18/19

2023-10-15 12:40 UTC, M1sterRob0t commented on src/hocs/withLoadingAndErrorHandling.tsx
> +  children: JSX.Element | undefined;
исправлено в задании 18/19

2023-10-15 12:54 UTC, M1sterRob0t commented on src/store/store.ts
> +      .concat(articlesApi.middleware)
тогда ругается тайпскрипт :(
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/79bc6f65-8ba3-43d5-8a98-7ed8e9114942)

2023-10-25 21:28 UTC, closed without merging