Feature/8
alyonastartseva/blogging-platform-2 pull request #18
Opened 2023-10-06 09:37 UTC by vovkahate

нужно только импорт поменять

2023-10-11 22:47 UTC, alyonastartseva requested changes

2023-10-11 22:47 UTC, alyonastartseva commented on src/components/blogCard/types.ts
> +export interface BlogDataFields {
BlogCardProps и BlogDataFields - одинаковые интерфейсы?

2023-10-11 22:47 UTC, alyonastartseva commented on src/components/blogsList/types.ts
> +export interface BlogDataFields {
в BLogCard аналогичный интерфейс - стоит вынести и использовать один

2023-10-12 21:26 UTC, vovkahate commented on src/components/blogCard/types.ts
> +export interface BlogDataFields {
удалил

2023-10-12 21:26 UTC, vovkahate commented on src/components/blogsList/types.ts
> +export interface BlogDataFields {
убрал там, оставил тут

2023-10-17 14:42 UTC, alyonastartseva approved these changes

2023-10-17 14:43 UTC, merged