Feature/20 theme switcher
alyonastartseva/blogging-platform-2 pull request #19
Opened 2023-10-06 10:12 UTC by vovkahate

умеет прееключать темы, сохранять состояние при перезагрузках страницы, инпут, селект и кнопка из антд поддерживают кастомный цвет когда появятся в проде, остальные элементы работают просто через темную-светлую дефолтную тему антд, другие цвета можно допилить по ходу.

2023-10-06 11:37 UTC, M1sterRob0t commented
В целом, дизайн выглядит очень круто и видно что была проделана большая работа в том, чтобы разобраться во всём этом. Наверное, самая сложная таска из всех что были. Я бы ей хард поставил, можно потом обсудить это с Алёной)

2023-10-09 14:26 UTC, M1sterRob0t requested changes

2023-10-11 23:26 UTC, alyonastartseva requested changes

2023-10-11 23:26 UTC, alyonastartseva commented on src/App.tsx
> +                        Input: {
идея с оберткой хорошая 👍🏻
давайте так и сделаем

2023-10-11 23:26 UTC, alyonastartseva commented on src/components/blogCard/BlogCard.module.scss
> +    // color: rgba(0, 0, 0, 0.65);
закомментированный код удалить либо раскомментить

2023-10-11 23:26 UTC, alyonastartseva commented on src/App.tsx
> +                        Input: {
'dark', 'light' и т.д лучше вынести в енамы

2023-10-12 12:40 UTC, vovkahate commented on src/App.tsx
> +                        Input: {
> Очень много лишней логики в App, которой тут быть не должно. Если ещё пару фич прикрутить в приложение и всё держать в app, то этот компонент превратится в свалку. Предлагаю вынести всю логику связанную с темой в HOC и оборачивать им компоненты, которым нужно реагировать на переключение темы.

я не знаю заранее какие будут на сайте добавлены компоненты, данный подход позвоялет применить тему на всё что будет добавлено позднее, а не переделывать тему после каждого ПРа

2023-10-17 20:54 UTC, alyonastartseva requested changes

2023-10-17 20:54 UTC, alyonastartseva commented on src/modules/themeSwitcher/slice.ts
> +    if (localStorage.getItem('theme') === 'dark') {
тернарником покрасивше будет

2023-10-17 20:56 UTC, alyonastartseva approved these changes

2023-10-17 20:58 UTC, merged