Closes 21 "Вёрстка страницы регистрации"
alyonastartseva/blogging-platform-2 pull request #23
Opened 2023-10-10 11:07 UTC by sc509

2023-10-11 12:42 UTC, M1sterRob0t commented
Чуть улучшить валидацию:
1. Ввод от двух символов в имя / фамилия
2. Запретить вводить кашу в поле имейла (просто тип у инпута поменять с  "текс" на "email"

И в принципе было бы корректней ввести одно поле username вместо lastName / firstName как на всех сайтах делают. А так всё гуд.
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/7c6fdc6c-a333-4819-b83a-513aae93cee5)

2023-10-13 13:46 UTC, M1sterRob0t commented
Ток сообщение поправь
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/0eeae98c-0c07-462e-a4fa-7ba832e90578)

2023-10-14 21:02 UTC, alyonastartseva requested changes

2023-10-17 11:57 UTC, alyonastartseva approved these changes

2023-10-17 11:57 UTC, merged