Feature/sort blogs by date
alyonastartseva/blogging-platform-2 pull request #25
Opened 2023-10-12 09:35 UTC by winston-0

Добавить сортировку блогов + подвязал rtk query для получения блогов

2023-10-17 10:13 UTC, M1sterRob0t commented on src/modules/blogs/components/blogs.tsx
> +  const {data, error, isLoading, isError} = useGetBlogsQuery(formQueryParams());
isError нигде не используется, убрать

2023-10-17 10:17 UTC, M1sterRob0t commented on src/modules/blogs/services/BlogListApi.tsx
> +  reducerPath: 'BlogListApi',
Переименовать везде BlogList (СписокБлога) => BlogsList (СписокБлогов)

2023-10-17 10:22 UTC, M1sterRob0t commented on src/store/root-reducer.ts
> +import BlogListSlice from '../modules/blogs/services/BlogListSlice';
в модульной архитектуре экспорт из модуля только через public API (индексный файл). Из недр модуля ничего не импортируется, по хорошему это запрещается линтером.
![273141259-d4619e07-6261-4c4c-8da5-569902b8f899](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/96b4cfb7-65d1-4d24-be3e-9dfeb0d4d2c1)

2023-10-19 11:45 UTC, alyonastartseva requested changes

2023-10-19 11:45 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +                options={[
options лучше вынести в константу (чтоб jsx не был перегружен) и проще читалось

2023-10-19 11:45 UTC, alyonastartseva commented on src/store/hooks.ts
> +import { TypedUseSelectorHook, useSelector } from 'react-redux'
уже есть в src/store/store.ts

2023-10-19 11:45 UTC, alyonastartseva commented on src/modules/blogs/components/blogs.tsx
> +        return {
а если добавится пагинация, поиск и т.д?

2023-10-23 18:05 UTC, alyonastartseva requested changes

2023-10-23 18:20 UTC, alyonastartseva requested changes

2023-10-23 18:20 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        { value: '', label: 'default' },
value и label будет лучше вынести в енамы и ниже, где используется 'default' label переиспользовать его там

так, в случае изменения какого-нибудь значения придётся менять в одном месте, а не в нескольких

2023-10-23 18:20 UTC, alyonastartseva commented on src/modules/blogs/components/blogs.tsx
> +  const options = useAppSelector((state) => state.blogsList)
tiny-замечания: пробелы облегчают жЫзнь и чтение кода :)

2023-10-23 18:20 UTC, alyonastartseva commented on src/modules/blogs/components/blogs.tsx
> +    const paramsObj = {} as TQueryParams
`as` выглядит костыльно

2023-10-25 21:25 UTC, alyonastartseva approved these changes

2023-10-25 21:25 UTC, merged