Closes 22  "Вёрстка страницы авторизации"
alyonastartseva/blogging-platform-2 pull request #26
Opened 2023-10-12 13:50 UTC by sc509

2023-10-16 10:51 UTC, M1sterRob0t commented
1. Password с маленькой буквы
2. Если loogin и есть email то лучше оставить просто email без всяких скобок, выглядит странно) 
Ну и тип email тогда добавить инпуту.
3. Показывает IncorrectPassword и красную обводку во время ввода пароля (зачем?)
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/1080199a-f3b1-47de-b069-1b3ceed6164a)

2023-10-17 07:16 UTC, M1sterRob0t commented
"Здесь же обработать ошибку в случае, если пароль неверный." Я думаю имелось ввиду, всё таки обработать по нажатию submit а не когда пользователь ввёл один символ)

2023-10-17 20:09 UTC, alyonastartseva requested changes

2023-10-17 20:09 UTC, alyonastartseva commented on src/modules/signIn/index.ts
пустой файлик

2023-10-17 20:09 UTC, alyonastartseva commented on src/modules/signIn/components/signIn.module.scss
> +.signInForm{
давай с SignUp-стилями объединение сделаем какое-нить (т.е общие стили вынести)

2023-10-17 20:09 UTC, alyonastartseva commented on src/modules/signIn/components/SignIn.tsx
> +    const onFinish = (values: SignInForm) => {
явного правильного пароля мы не увидим при интеграции с бэком - нам будет просто приходить ошибка
поэтому давай уберем хардкод passwordInput и добавим в комментариях установку ошибки и будет гуд

```
const onFinish = (values: SignInForm) => {
        // form.setFields([
                {name: 'password', errors: ['The password is incorrect.']}
            ]);
    };
```

2023-10-23 17:01 UTC, merged