Feature/article create layout
alyonastartseva/blogging-platform-2 pull request #5
Opened 2023-09-30 04:40 UTC by sc509

closes [Task 5]

2023-09-30 05:53 UTC, M1sterRob0t commented
1. Создаёшь форму создания блога, почему название компонента createArticle a не createBlog? Ведь в проекте есть ещё и форма создания статьи, как тогда назвать её?:)

2. Где тайпскрипт?:) Добавить типизацию, убрать тип any отовсюду

3. Name blog => Blog name, переименовать

2023-09-30 05:56 UTC, M1sterRob0t commented
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/d68aa2fc-b9b9-4135-9254-6ec008cdabef)

2023-09-30 07:39 UTC, Sv812asx commented
1.+
2.+
3.+
4.+

2023-09-30 10:21 UTC, M1sterRob0t commented
![image](https://github.com/alyonastartseva/blogging-platform-2/assets/35527937/41562af8-bdc8-497d-860d-68815309cba3)
А это что?

2023-10-03 08:55 UTC, alyonastartseva requested changes

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.module.scss
> +.antForm{
класс лучше назвать не завязываясь на Ant: createForm/createBlogForm и т.д (чтобы не было путаницы)

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +    const {antForm, antFormLabel, antFormTitle, antFormInput, antFormSubmit} = styles;
все, что не меняется в компоненте - выносить из него

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +interface FormValues {
типы/интерфейсы лучше размещать рядом в createBlog.type.ts

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +    const [hasImageUploaded, setHasImageUploaded] = useState<boolean>(true);
явно указывать boolean не обязательно, так как тип выводится при инициализации значением true

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +            })
можно сразу заложить вывод сообщения об ошибке - в Анте есть message-компонент

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +                    style={{maxWidth: 700}}
лучше придерживаться одного стиля и в случае использования scss выносить стили туда

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +    const isSameDay = (date1: dayjs.Dayjs, date2: Date) => {
эту функцию лучше вынести в shared-слой, так как наверняка может использоваться в других компонентах

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +        <>
фрагмент нельзя убрать?

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/createBlog/createBlog.tsx
> +                                    <div style={{ marginTop: 8 }}>Upload</div>
аналогично про стили

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +    const {inputs} = styles;
вынести из компонента

2023-10-03 08:55 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        navigate('/create-blog');
сейчас логика написана через отдельную страничку
по задачке - должно быть модальное окно => нужно убрать роутинг, а при клике по попке менять состояние видимости модалки

2023-10-03 12:30 UTC, Sv812asx commented on src/components/createBlog/createBlog.module.scss
> +.antForm{
+

2023-10-03 12:42 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +    const {antForm, antFormLabel, antFormTitle, antFormInput, antFormSubmit} = styles;
+

2023-10-03 12:45 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +interface FormValues {
+

2023-10-03 12:45 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +    const [hasImageUploaded, setHasImageUploaded] = useState<boolean>(true);
+

2023-10-03 13:03 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +                                    <div style={{ marginTop: 8 }}>Upload</div>
+

2023-10-03 13:11 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +    const isSameDay = (date1: dayjs.Dayjs, date2: Date) => {
+

2023-10-03 13:12 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +        <>
+

2023-10-03 13:16 UTC, Sv812asx commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +    const {inputs} = styles;
+

2023-10-03 13:18 UTC, Sv812asx commented on src/components/createBlog/createBlog.tsx
> +                    style={{maxWidth: 700}}
+

2023-10-03 14:11 UTC, Sv812asx commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        navigate('/create-blog');
+

2023-10-04 16:11 UTC, alyonastartseva requested changes

2023-10-04 16:11 UTC, alyonastartseva commented on src/modules/CreateBlogForm/store/store.ts
> +import { combineReducers, configureStore } from "@reduxjs/toolkit";
store будут потреблять все компоненты, поэтому лучше его вынести из CreateBlogForm

2023-10-04 16:11 UTC, alyonastartseva commented on src/modules/CreateBlogForm/slice/modal-slice.ts
> +
зачем стейт для модалки?

2023-10-04 16:11 UTC, alyonastartseva commented on src/modules/CreateBlogForm/slice/modal-slice.ts
> +
чтобы избежать создания стейта достаточно в createBlog передать пропс visibility

2023-10-04 16:11 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        if (e.target === e.currentTarget) {
при использовании Modal из Ант это можно опустить

2023-10-04 16:11 UTC, alyonastartseva commented on src/components/indexPageInputs/indexPageInputsStyles.ts
> +export const inputs = styles.inputs;
а почему бы сразу в tsx styles не заиспользовать?

2023-10-04 16:11 UTC, alyonastartseva commented on src/modules/CreateBlogForm/components/createBlog/createBlogStyles.ts
> +export const blogFormInput = styles.blogFormInput;
аналогично: можно сразу styles заиспользовать в tsx-компоненте

2023-10-04 16:11 UTC, alyonastartseva commented on src/components/indexPageInputs/IndexpageInputs.module.scss
> +    top: 0;
если не используешь модалку для Анта, то лучше делать собственный компонент через createPortal

2023-10-04 16:29 UTC, Sv812asx commented on src/shared/isSameDayUtils.ts
> +import dayjs from "dayjs";
+

2023-10-04 16:44 UTC, Sv812asx commented on src/modules/CreateBlogForm/store/store.ts
> +import { combineReducers, configureStore } from "@reduxjs/toolkit";
+

2023-10-04 16:55 UTC, Sv812asx commented on src/modules/CreateBlogForm/slice/modal-slice.ts
> +
+

2023-10-04 16:56 UTC, Sv812asx commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        if (e.target === e.currentTarget) {
Не юзаю ant modal

2023-10-04 16:58 UTC, Sv812asx commented on src/modules/CreateBlogForm/components/createBlog/createBlogStyles.ts
> +export const blogFormInput = styles.blogFormInput;
+

2023-10-04 17:07 UTC, Sv812asx commented on src/components/indexPageInputs/IndexPageInputs.tsx
> +        if (e.target === e.currentTarget) {
Посмотрел createPortal,принял решение, что буду всё таки юзать ant modal

2023-10-04 21:03 UTC, alyonastartseva requested changes

2023-10-04 21:03 UTC, alyonastartseva commented on src/Utils/date.ts
для единообразия папку с маленькой буквы лучше назвать

2023-10-04 21:03 UTC, alyonastartseva commented on src/modules/CreateBlogForm/components/createBlog/createBlog.tsx
> +function CreateBlog({ isOpen, setIsModalVisible }: {isOpen: boolean, setIsModalVisible: (open: boolean) => void}) {
более читабельно вынести тип пропсов и положить уже в существующий type-файл

2023-10-05 04:53 UTC, Sv812asx commented on src/Utils/date.ts
+

2023-10-07 08:35 UTC, merged

2023-10-07 11:44 UTC, alyonastartseva commented on src/modules/CreateBlogForm/components/CreateBlog/createBlog.tsx
> +            title={<div className={styles.modalTitle}>Create blog</div>}
если div создан лишь для накатывания стилей, то лучше в Modal передать className и "перебить" Антоновский стили:

`.createBlogModal .ant-modal-header { ... }`