Feature/create article feature
alyonastartseva/blogging-platform-2 pull request #6
Opened 2023-09-30 14:17 UTC by Groupmk

2023-10-01 16:10 UTC, M1sterRob0t commented
1.  Очень узкая форма, с полем контент статьи дико неудобно работать, зато по бокам куча свободного пустого места. Может можно форму сделать пошире?)
2.  Почему названия полей и ошибки на русском? Всё делаем на английском.
3. Не поправил лейбл "Заголовок статьи", всё ещё залазит под инпут
4. Можно добавлять одинаковые теги. Лучше заблокировать эту возможность заранее, чтобы потом не было ошибок, иначе придётся вводить id для каждого тега.

2023-10-02 20:59 UTC, alyonastartseva requested changes

2023-10-02 20:59 UTC, alyonastartseva commented on db-1695929535824.json
a db-файл не server/db.json?

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +import { Button } from 'antd';
забудлировались импорты

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +interface FormData {
типы/интерфейсы лучше выносить в отдельный файл рядом с компонентой: createArticle.type.ts || types.ts

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const [editorValue, setEditorValue] = useState<string>('');
объявлять тип излишне, т.к. он выводится при присваивании пусто строки (ниже аналогично в стейтах)

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const defaultTags = ['tag1', 'tag2', 'tag3'];
константы лучше тоже выносить:
createArticle.constants.ts

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const { container } = Style;
деструктуризацию лучше вынести из компонента: всё, на что не влияет компонент - лучше выносить из него

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const modules = {
аналогично (вынести в константы рядом)

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +    if (selectedTagValues.length <= 5) {
5 - магическая переменная, вынести в константу

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const showModal = () => {
showModal и handleCancel можно объединить, так как функции делают одно и то же (меняют видимость модалки) на, например, changeVisibility(isVisible: boolean)

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +        <Form {...formItemLayout} onFinish={onFinish} style={{ padding: '50px', marginLeft: '-150px' }}>
лучше придерживаться одного стиля и в случае использования scss выносить стили туда

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +              <div style={{ color: 'red' }}>Cannot select more than 5 tags!</div>
в Ant'е для форм есть метод setFields, помогающий устанавливать статус и сообщение (в случай шибок)
тем самым этот div канет в лету

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +              <div style={{ color: 'red' }}>Tag must be unique!</div>
и вот этот

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +          <Form.Item wrapperCol={{ offset: 6, span: 140 }}>
лучше вынести в константу (как сверху делал) и ниже этот пропс есть

2023-10-02 20:59 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +            <Button type="primary" onClick={addCustomTag} style={{ marginTop: '1.5rem' }}>
аналогично про стили - перенос в scss

2023-10-03 16:24 UTC, alyonastartseva requested changes

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  options.push({
а это зачем?

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +import type { ColProps, SelectProps } from 'antd';
два подряд импорта из antd

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +  const [selectedTags, setSelectedTags] = useState<string[]>([]);
state уже не нужен

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +      value = value.slice(0, maxTagCounts);
параметры переопределять плохая затея

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +const formItemLayout = {
если создал файл для констант, то эти лучше тоже туда перенести

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +          <Form.Item label="Tags" name={'tags'}>
name="tags"

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/createArticleForm/modulesReactQuill.ts
> +export const modules = {
можно в константс закинуть

2023-10-03 16:24 UTC, alyonastartseva commented on src/modules/header/Header.tsx
> +            <CreateArticle />
из хедера не убрал компонентику

2023-10-04 16:45 UTC, alyonastartseva requested changes

2023-10-04 16:45 UTC, alyonastartseva commented on src/modules/createArticleForm/CreateArticle.tsx
> +    let newSelectedTags = value;
массив как хранит значение? :) по ссылке или значению?

2023-10-04 20:11 UTC, merged